Allow passing argument to build, as before
Only add info & confirmation steps for builds on:

- develop,
- validation,
- release.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -3,10 +3,6 @@ set -euo pipefail
 
 TARGET="${1:-default}"
 
-scripts/info-branch-commit
-export readonly TARGET=$(scripts/option-prompt "Select a target" vm develop validation master lab-key shed-key stuck default)
-echo
-
 # Allow unfree packages, required for zerotier using a BSL 1.1 licence
 # See https://nixos.wiki/wiki/FAQ/How_can_I_install_a_proprietary_or_unfree_package%3F
 export NIXPKGS_ALLOW_UNFREE=1
@@ -36,6 +32,9 @@ You can switch virtual consoles in the guest via QEMU monitor (ctrl-alt-2), send
 
 elif [ "$TARGET" == "develop" ]; then
 
+  scripts/info-branch-commit
+  scripts/confirm-or-abort
+
   (set -x; nix-build \
     --arg updateCert ./pki/develop/cert.pem \
     --arg updateUrl https://dist.dividat.com/releases/playos/develop/ \
@@ -48,6 +47,9 @@ elif [ "$TARGET" == "develop" ]; then
 
 elif [ "$TARGET" == "validation" ]; then
 
+  scripts/info-branch-commit
+  scripts/confirm-or-abort
+
   (set -x; nix-build \
     --arg updateCert ./pki/validation/cert.pem \
     --arg updateUrl https://dist.dividat.com/releases/playos/validation/ \
@@ -59,6 +61,9 @@ elif [ "$TARGET" == "validation" ]; then
   echo "Run ./result/bin/deploy-update to deploy."
 
 elif [ "$TARGET" == "master" ]; then
+
+  scripts/info-branch-commit
+  scripts/confirm-or-abort
 
   (set -x; nix-build \
     --arg updateCert ./pki/master/cert.pem \
@@ -101,8 +106,15 @@ elif [ "$TARGET" == "shed-key" ]; then
     --arg buildBundle false \
     --arg buildDisk false)
 
-else
+elif [ "$TARGET" == "default" ]; then
 
   (set -x; nix-build)
+
+else
+
+  echo
+  echo "I do not know how to build '$TARGET'."
+  echo "Aborting."
+  exit 1
 
 fi
