Prevent usage of quick build mode for "production" targets

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,8 +1,16 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
+# targets which produce releases and deployments, prevents usage of QUICK_BUILD
+PRODUCTION_TARGETS="develop|validation|master|release-disk"
+
+# other targets used for development/testing/etc
+OTHER_TARGETS="vm|stuck|lab-key|shed-key|test-e2e|all"
+
+ALL_TARGETS="$PRODUCTION_TARGETS|$OTHER_TARGETS"
+
 usage() {
-  echo "Usage: $0 [--quick] {vm|develop|validation|master|stuck|lab-key|shed-key|test-e2e|release-disk|all}"
+  echo "Usage: $0 [--quick] {$ALL_TARGETS}"
   exit 1
 }
 
@@ -23,6 +31,12 @@ done
 
 if [[ -z "$TARGET" ]]; then
   usage
+fi
+
+if [[ ! -z "${QUICK_BUILD:-}" ]] && [[ "$PRODUCTION_TARGETS" =~ "$TARGET" ]]; then
+    echo "Error: QUICK_BUILD mode not allowed for target '$TARGET', aborting."
+    echo "       Remove --quick and/or make sure QUICK_BUILD env var is unset"
+    exit 11
 fi
 
 
